"""Banco de dados inicial resumido

Revision ID: 432ef8b7cbde
Revises: 
Create Date: 2026-04-05 21:13:09.615689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432ef8b7cbde'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarefas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('criador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criador'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_tarefa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('concluido', sa.Boolean(), nullable=True),
    sa.Column('tarefa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tarefa'], ['tarefas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_tarefa')
    op.drop_table('tarefas')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
